services:
  - type: web
    name: hausly-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install --include=dev && npx prisma generate && npm run build
    startCommand: cd backend && node dist/src/main.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
